name: 07 - Using Expressions
run-name: 07 - Using Expressions ${{inputs.debug}} && 'ON' || 'OFF'
on:
  push:
  workflow_dispatch:
    inputs:
      debug:
        type: boolean
        default: false


jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: "[debug] Print start-up data"
        if: ${{ inputs.debug }}
        run: |
          echo "Triggered By: ${{ github.event_name }}"
          echo "Branch: ${{ github.ref }}"
          echo "Commit SHA: ${{ github.SHA }}"
          echo "Runner By: ${{ Runner.os }}"
      - name: '[debug] Print when triggere from main'
        if: ${{ inputs.debug && github.ref == 'refs/heads/main'}}
        run: |
          echo "I was Triggered from main"
      - name: Greeting
        run: echo "Hello, World"
